code_prefix: "我是爱坤我不是小黑子"
# mysql地址
db_host: "localhost"
# mysql端口
db_port: 3360
# mysql用户名
db_user: "tcc"
# mysql密码
db_passwd: "TccServer2024@"
# 所用数据库
db_database: "tcc"
# true是随机黑名单模式, false是随机白名单模式.
gift_blacklist: true
