name: KikiWhitelist
version: '${version}'
main: com.tinyshellzz.kikiwhitelist.KIkiWhitelist
api-version: '1.20'
folia-supported: true
commands:
  kiki:
    description: KikiWhitelist plugin management
    default: false
  iban:
    description: KikiWhitelist iban command
    usage: /iban <name> <time> <remark>
    # "default: true" for everyone
    # or use "permission: kiki.iban", and you can set "permission-message: ..."
    default: true
  iunban:
    description: KikiWhitelist iunban command
    usage: /iunban <name>
    default: true
  redeem:
    description: daly sign in redeem command
    usage: /redeem <code>
    default: true
    permission: redeem.use
  rewards:
    description: daly sign in command rewards
    usage: /rewards save <day>
    default: false
    permission: kiki.use